version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"
  # deploy_contracts:
  #   build:
  #     context: .
  #     target: deploy-contracts
  relayer:
    build:
      context: .
      target: relayer
      dockerfile: Dockerfile-relayer
    ports:
      - "8080:8080"

  resolver:
    build:
      context: .
      target: resolver
      dockerfile: Dockerfile-resolver
    ports:
      - "8001:8001"
