# ANSI color codes
COLOR_GREEN=\033[32m
COLOR_RESET=\033[0m

# Variables.
ENVIRONMENT       ?=
IMAGE_TAG         ?= latest
REGISTRY_HOST     ?= ghcr.io/boostylabs
CURRENT_DATE_TIME := $(shell date +'%Y-%m-%d')
LATEST_COMMIT     := $$(git rev-parse --short HEAD)

#Dockerfile name.
RESOLVER_DOCKERFILE := ./resolver/Dockerfile
RELAYER_DOCKERFILE := ./relayer/Dockerfile
# Image names.
RESOLVER_IMAGE_NAME := 1inch-resolver
RELAYER_IMAGE_NAME := 1inch-relayer

IMAGE_RESOLVER_BACKUP = $(REGISTRY_HOST)/$(RESOLVER_IMAGE_NAME)$(ENVIRONMENT):$(CURRENT_DATE_TIME)-$(LATEST_COMMIT)
IMAGE_RESOLVER_LATEST = $(REGISTRY_HOST)/$(RESOLVER_IMAGE_NAME)$(ENVIRONMENT):$(IMAGE_TAG)

IMAGE_RELAYER_BACKUP = $(REGISTRY_HOST)/$(RELAYER_IMAGE_NAME)$(ENVIRONMENT):$(CURRENT_DATE_TIME)-$(LATEST_COMMIT)
IMAGE_RELAYER_LATEST = $(REGISTRY_HOST)/$(RELAYER_IMAGE_NAME)$(ENVIRONMENT):$(IMAGE_TAG)