version: '3.8'

services:
  blockchain:
    container_name: blockchain
    image: ghcr.io/foundry-rs/foundry:v0.3.0
    # platform: linux/amd64
    entrypoint: "anvil --host 0.0.0.0"
    ports:
      - "8545:8545"
    healthcheck:
      test: cast chain-id
      interval: 5s
    networks:
      - fullstack

  deploy-contract:
    image: ghcr.io/foundry-rs/foundry:v0.3.0
    entrypoint: "forge create --broadcast --private-key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://blockchain:8545 /contracts/NodeRegistry.sol:NodeRegistry"
    volumes:
      - "./contracts:/contracts"
    depends_on:
      blockchain:
        condition: service_healthy
    networks:
      - fullstack

  relayer:
    container_name: relayer
    build:
      context: .
      target: relayer
      dockerfile: ./relayer/Dockerfile
    volumes:
      - "./assets/relayer.config.yaml:/app/config.yaml"
    entrypoint: ["/bin/sh", "-c", "./main run --config config.yaml"]
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "15000-15500:15000-15500"
    networks:
      - fullstack
      - test

  resolver:
    container_name: resolver
    build:
      context: .
      target: resolver
      dockerfile: ./resolver/Dockerfile
    volumes:
      - "./assets/resolver.config.yaml:/app/config.yaml"
    entrypoint: ["/bin/sh", "-c", "./main register --config_file config.yaml; ./main run --config_file config.yaml"]
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
    ports:
      - "8001:8001"
      - "8081:8081"
    networks:
      - fullstack

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - fullstack

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./assets/provisioning:/etc/grafana/provisioning
    environment:
      # Default Grafana admin password; change as needed.
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
  test:
    driver: ipvlan
