global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'relayer'
    static_configs:
      - targets: ['relayer:8080']
  - job_name: 'resolver'
    static_configs:
      - targets: ['resolver:8081']
