{
 "title": "Resolver Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grpc_server_connections_open" }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grpc_server_connections_total" }
   ]
  },
  {
   "title": "Total Requests (method 'Execute')",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_requests_total{grpc_method=\"Execute\"}"
    }
   ]
  },
  {
   "title": "Request Duration Avg (method 'Execute')",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_latency_seconds_sum{grpc_code=\"OK\",grpc_method=\"Execute\"} / grpc_server_latency_seconds_count{grpc_code=\"OK\",grpc_method=\"Execute\"}"
    }
   ]
  },
  {
   "title": "Received Bytes (method 'Execute')",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_recv_bytes_sum{grpc_method=\"Execute\"})"
    }
   ]
  },
  {
   "title": "Sent Bytes (method 'Execute')",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_sent_bytes_sum{grpc_method=\"Execute\"})"
    }
   ]
  },
  {
   "title": "Pending Requests (method 'Execute')",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_requests_pending{grpc_method=\"Execute\"})"
    }
   ]
  }
 ]
}