log_level: DEBUG
http_endpoint: relayer:8080
webrtc_ice_server: stun:stun1.l.google.com:19302
grpc_server_address: resolver:8001
blockchain_rpc_address: "http://blockchain:8545"
contract_address: 0x5fbdb2315678afecb367f032d93f642f64180aa3
private_key: 59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
retry_request:
  enabled: false
  count: 5
  interval: 1s
peers_port_range:
  enabled: true
  min: 15000
  max: 15500
