{
 "title": "Relayer Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active PeerConnections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "relayer_active_peer_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages disposition",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (session_id)(relayer_data_channel_messages_sent_total{status=\"success\"})",
     "legendFormat": "Sent Success"
    },
    {
     "expr": "sum by (session_id)(relayer_data_channel_messages_received_total)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (session_id)(relayer_data_channel_messages_sent_total{status=\"failed\"})",
     "legendFormat": "Send Failed"
    }
   ]
  },
  {
   "title": "gRPC call status rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, status)(rate(relayer_grpc_requests_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (handler, status)(rate(relayer_http_requests_total{handler=~\"^/(sdp|candidate)$\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDP Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le)(rate(relayer_http_request_duration_seconds_bucket{handler=\"/sdp\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDP Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/sdp\"}[1m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/sdp\"}[1m])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/sdp\"}[1m])) by (le))",
     "legendFormat": "99th quantile"
    }
   ]
  },
  {
   "title": "Received Candidate latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (le)(rate(relayer_http_request_duration_seconds_bucket{handler=\"/candidate\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Candidate latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/candidate\"}[1m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/candidate\"}[1m])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(relayer_http_request_duration_seconds_bucket{handler=\"/candidate\"}[1m])) by (le))",
     "legendFormat": "99th quantile"
    }
   ]
  },
  {
   "title": "gRPC Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (le)(rate(relayer_grpc_request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(relayer_grpc_request_duration_seconds_bucket[1m])))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(relayer_grpc_request_duration_seconds_bucket[1m])))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(relayer_grpc_request_duration_seconds_bucket[1m])))",
     "legendFormat": "50th quantile"
    }
   ]
  }
 ]
}