name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, edited]
  push:
    branches:
      - 'main'

jobs:
  verify_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linelint
        uses: fernandrone/linelint@0.0.6
        id: linelint

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --timeout 5m

      - name: Check compilation
        run: |
          make build
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Verify Anvil Installation
        run: anvil --version

      - name: Start Anvil
        run: |
          make start-anvil

      - name: Deploy Contract
        run: |
          make deploy_contract

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.0

      - name: Run tests
        run: |
          make testsum
